export enum AppEvents {
  GET_USER = 'APP/GET_FETCH_USER',
  GET_PREFRENCE = 'APP/GET_FETCH_PREFRENCE',

  SET_USER = 'APP/SET_USER',
  SET_TOUR_VISIBILITY = 'APP/SET_TOUR_VISIBILITY',

  SET_QUESTIONANSWER = 'APP/SET_QUESTIONANSWER',
  GET_QUESTIONANSWER = 'APP/GET_QUESTIONANSWER',
}
